all:
	gcc -lm -fopenmp -O3 omp_Jacob.c -o omp_Jacob
	gcc -lm -fopenmp -O3 omp_GaussSeidel1.c -o omp_GaussSeidel1
	gcc -lm -fopenmp -O3 omp_SOR.c -o omp_SOR
	gcc -lm -fopenmp -O3 omp_CG.c -o omp_CG

compile:

